import type { FileType, FileTypeConfig } from "@/types";

/* ─────────────────────────────────────────────────────────────
   Each file type declares:
     • headerSignatures – lowercased strings unique to its headers
     • expectedColumns  – canonical output column names
     • requiredFields   – columns that must be non-empty
     • dateColumns      – columns validated & normalized as dates
     • numericColumns   – columns validated as numbers
     • columnNameMap    – raw header (lowercased) → canonical name
     • textCasingRules  – per-column casing enforcement
     • dateFormat       – output date format  (YYYY-MM-DD)
   ───────────────────────────────────────────────────────────── */

const FILE_TYPE_CONFIGS: Record<FileType, FileTypeConfig> = {
  ACCOUNT_STATUS_BEL: {
    id: "ACCOUNT_STATUS_BEL",
    name: "Account Status BEL",
    headerSignatures: ["account number", "account status", "bel"],
    expectedColumns: [
      "Account Number",
      "Account Name",
      "Account Status",
      "Balance",
      "Due Date",
      "Last Payment Date",
      "Contact Number",
      "Email",
      "Region",
      "Remarks",
    ],
    requiredFields: ["Account Number", "Account Name", "Account Status", "Balance"],
    dateColumns: ["Due Date", "Last Payment Date"],
    numericColumns: ["Balance"],
    columnNameMap: {
      "account number": "Account Number",
      "account no": "Account Number",
      "account no.": "Account Number",
      "acct no": "Account Number",
      "account name": "Account Name",
      "acct name": "Account Name",
      "account status": "Account Status",
      status: "Account Status",
      balance: "Balance",
      "outstanding balance": "Balance",
      "total balance": "Balance",
      amount: "Balance",
      "due date": "Due Date",
      "last payment date": "Last Payment Date",
      "last payment": "Last Payment Date",
      "contact number": "Contact Number",
      "contact no": "Contact Number",
      phone: "Contact Number",
      email: "Email",
      "email address": "Email",
      region: "Region",
      area: "Region",
      remarks: "Remarks",
      notes: "Remarks",
      comment: "Remarks",
    },
    textCasingRules: {
      "Account Name": "title",
      "Account Status": "upper",
      Region: "upper",
    },
    dateFormat: "YYYY-MM-DD",
  },

  ADA_PENALTY: {
    id: "ADA_PENALTY",
    name: "ADA Penalty",
    headerSignatures: ["penalty", "ada", "violation"],
    expectedColumns: [
      "Reference Number",
      "Account Number",
      "Account Name",
      "Penalty Type",
      "Penalty Amount",
      "Violation Date",
      "Due Date",
      "Status",
      "Remarks",
    ],
    requiredFields: ["Reference Number", "Account Number", "Penalty Amount", "Violation Date"],
    dateColumns: ["Violation Date", "Due Date"],
    numericColumns: ["Penalty Amount"],
    columnNameMap: {
      "reference number": "Reference Number",
      "ref no": "Reference Number",
      "ref number": "Reference Number",
      "reference no": "Reference Number",
      "account number": "Account Number",
      "account no": "Account Number",
      "acct no": "Account Number",
      "account name": "Account Name",
      "acct name": "Account Name",
      "penalty type": "Penalty Type",
      type: "Penalty Type",
      "penalty amount": "Penalty Amount",
      penalty: "Penalty Amount",
      amount: "Penalty Amount",
      "violation date": "Violation Date",
      "date of violation": "Violation Date",
      "due date": "Due Date",
      status: "Status",
      remarks: "Remarks",
      notes: "Remarks",
    },
    textCasingRules: {
      "Account Name": "title",
      "Penalty Type": "upper",
      Status: "upper",
    },
    dateFormat: "YYYY-MM-DD",
  },

  BSP_ATTESTATION: {
    id: "BSP_ATTESTATION",
    name: "BSP Attestation",
    headerSignatures: ["attestation", "bsp", "compliance"],
    expectedColumns: [
      "Reference Number",
      "Account Number",
      "Account Name",
      "Attestation Date",
      "Compliance Status",
      "Attested By",
      "Department",
      "Remarks",
    ],
    requiredFields: ["Reference Number", "Account Number", "Attestation Date", "Compliance Status"],
    dateColumns: ["Attestation Date"],
    numericColumns: [],
    columnNameMap: {
      "reference number": "Reference Number",
      "ref no": "Reference Number",
      "ref number": "Reference Number",
      "account number": "Account Number",
      "account no": "Account Number",
      "acct no": "Account Number",
      "account name": "Account Name",
      "acct name": "Account Name",
      "attestation date": "Attestation Date",
      date: "Attestation Date",
      "compliance status": "Compliance Status",
      compliance: "Compliance Status",
      status: "Compliance Status",
      "attested by": "Attested By",
      "prepared by": "Attested By",
      department: "Department",
      dept: "Department",
      remarks: "Remarks",
      notes: "Remarks",
    },
    textCasingRules: {
      "Account Name": "title",
      "Compliance Status": "upper",
      "Attested By": "title",
      Department: "upper",
    },
    dateFormat: "YYYY-MM-DD",
  },

  PTP_REPORT_BEL: {
    id: "PTP_REPORT_BEL",
    name: "PTP Report BEL",
    headerSignatures: ["ptp", "promise to pay", "report"],
    expectedColumns: [
      "Account Number",
      "Account Name",
      "PTP Date",
      "PTP Amount",
      "Agent Name",
      "Contact Number",
      "Status",
      "Follow Up Date",
      "Remarks",
    ],
    requiredFields: ["Account Number", "PTP Date", "PTP Amount", "Status"],
    dateColumns: ["PTP Date", "Follow Up Date"],
    numericColumns: ["PTP Amount"],
    columnNameMap: {
      "account number": "Account Number",
      "account no": "Account Number",
      "acct no": "Account Number",
      "account name": "Account Name",
      "acct name": "Account Name",
      "ptp date": "PTP Date",
      "promise date": "PTP Date",
      "promise to pay date": "PTP Date",
      "ptp amount": "PTP Amount",
      "promise amount": "PTP Amount",
      amount: "PTP Amount",
      "agent name": "Agent Name",
      agent: "Agent Name",
      "contact number": "Contact Number",
      "contact no": "Contact Number",
      phone: "Contact Number",
      status: "Status",
      "ptp status": "Status",
      "follow up date": "Follow Up Date",
      "followup date": "Follow Up Date",
      "follow-up date": "Follow Up Date",
      remarks: "Remarks",
      notes: "Remarks",
    },
    textCasingRules: {
      "Account Name": "title",
      "Agent Name": "title",
      Status: "upper",
    },
    dateFormat: "YYYY-MM-DD",
  },

  PTP_INVENTORY_BEL: {
    id: "PTP_INVENTORY_BEL",
    name: "PTP Inventory BEL",
    headerSignatures: ["ptp", "inventory", "bel"],
    expectedColumns: [
      "Account Number",
      "Account Name",
      "PTP Date",
      "PTP Amount",
      "Paid Amount",
      "Balance",
      "Status",
      "Disposition",
      "Agent Name",
      "Remarks",
    ],
    requiredFields: ["Account Number", "PTP Date", "PTP Amount", "Status"],
    dateColumns: ["PTP Date"],
    numericColumns: ["PTP Amount", "Paid Amount", "Balance"],
    columnNameMap: {
      "account number": "Account Number",
      "account no": "Account Number",
      "acct no": "Account Number",
      "account name": "Account Name",
      "acct name": "Account Name",
      "ptp date": "PTP Date",
      "promise date": "PTP Date",
      "ptp amount": "PTP Amount",
      "promise amount": "PTP Amount",
      "paid amount": "Paid Amount",
      paid: "Paid Amount",
      balance: "Balance",
      "remaining balance": "Balance",
      status: "Status",
      "ptp status": "Status",
      disposition: "Disposition",
      "agent name": "Agent Name",
      agent: "Agent Name",
      remarks: "Remarks",
      notes: "Remarks",
    },
    textCasingRules: {
      "Account Name": "title",
      "Agent Name": "title",
      Status: "upper",
      Disposition: "upper",
    },
    dateFormat: "YYYY-MM-DD",
  },

  CARDS_ATTENDANCE: {
    id: "CARDS_ATTENDANCE",
    name: "Cards Attendance",
    headerSignatures: ["attendance", "cards", "time in", "time out"],
    expectedColumns: [
      "Employee ID",
      "Employee Name",
      "Date",
      "Time In",
      "Time Out",
      "Hours Worked",
      "Status",
      "Department",
      "Remarks",
    ],
    requiredFields: ["Employee ID", "Employee Name", "Date", "Status"],
    dateColumns: ["Date"],
    numericColumns: ["Hours Worked"],
    columnNameMap: {
      "employee id": "Employee ID",
      "emp id": "Employee ID",
      "employee no": "Employee ID",
      "employee name": "Employee Name",
      "emp name": "Employee Name",
      name: "Employee Name",
      date: "Date",
      "attendance date": "Date",
      "time in": "Time In",
      "clock in": "Time In",
      "time out": "Time Out",
      "clock out": "Time Out",
      "hours worked": "Hours Worked",
      hours: "Hours Worked",
      "total hours": "Hours Worked",
      status: "Status",
      "attendance status": "Status",
      department: "Department",
      dept: "Department",
      remarks: "Remarks",
      notes: "Remarks",
    },
    textCasingRules: {
      "Employee Name": "title",
      Status: "upper",
      Department: "upper",
    },
    dateFormat: "YYYY-MM-DD",
  },

  FIELD_VISIT_REPORT_BEL: {
    id: "FIELD_VISIT_REPORT_BEL",
    name: "Field Visit Report BEL",
    headerSignatures: ["field visit", "visit date", "visit report"],
    expectedColumns: [
      "Account Number",
      "Account Name",
      "Visit Date",
      "Visit Time",
      "Field Agent",
      "Address",
      "Findings",
      "Disposition",
      "Status",
      "Next Action Date",
      "Remarks",
    ],
    requiredFields: ["Account Number", "Visit Date", "Field Agent", "Status"],
    dateColumns: ["Visit Date", "Next Action Date"],
    numericColumns: [],
    columnNameMap: {
      "account number": "Account Number",
      "account no": "Account Number",
      "acct no": "Account Number",
      "account name": "Account Name",
      "acct name": "Account Name",
      "visit date": "Visit Date",
      "date of visit": "Visit Date",
      "visit time": "Visit Time",
      time: "Visit Time",
      "field agent": "Field Agent",
      agent: "Field Agent",
      "agent name": "Field Agent",
      address: "Address",
      "visit address": "Address",
      findings: "Findings",
      "visit findings": "Findings",
      disposition: "Disposition",
      status: "Status",
      "visit status": "Status",
      "next action date": "Next Action Date",
      "follow up date": "Next Action Date",
      "next visit date": "Next Action Date",
      remarks: "Remarks",
      notes: "Remarks",
    },
    textCasingRules: {
      "Account Name": "title",
      "Field Agent": "title",
      Disposition: "upper",
      Status: "upper",
    },
    dateFormat: "YYYY-MM-DD",
  },
};

export default FILE_TYPE_CONFIGS;

export function getAllFileTypes(): FileTypeConfig[] {
  return Object.values(FILE_TYPE_CONFIGS);
}

export function getFileTypeConfig(fileType: FileType): FileTypeConfig {
  return FILE_TYPE_CONFIGS[fileType];
}
